import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Failure,primary,input} from '@/components/agentCenter/ui';
import TemplateMessage from '@/components/agentCenter/TemplateMessage';
export default function ProjectReadyAgent({project}) {
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[text,setText]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let live=true;async function open(){setLoading(true);try{const list=await base44.agents.listConversations({agent_name:'hub_project_celebrator'});const entries=Array.isArray(list)?list:list?.conversations||[];const key=`${project.id}:${project.ready_at}`;const previous=entries.find(item=>item.metadata?.description===key);if(previous){const full=await base44.agents.getConversation(previous.id);if(live){setConversation(full);setMessages(full.messages||[])}}else{const current=await base44.agents.createConversation({agent_name:'hub_project_celebrator',metadata:{name:`${project.name} is ready`,description:key}});if(!live)return;setConversation(current);await base44.agents.addMessage(current,{role:'user',content:`[Project ready event]\nProject: ${project.name}\nGoal: ${(project.summary||'Not provided').slice(0,300)}\nThe project's status changed to Ready to Use. Please congratulate me.`})}}catch(e){if(live)setError(e.message||'Could not open the celebration.')}finally{if(live)setLoading(false)}}open();return()=>{live=false}},[project.id,project.ready_at]);
  useEffect(()=>{if(!conversation?.id)return;return base44.agents.subscribeToConversation(conversation.id,data=>setMessages(data.messages||[]))},[conversation?.id]);
  async function send(e){e.preventDefault();const content=text.trim();if(!content||!conversation||busy)return;setBusy(true);setError('');try{setText('');setMessages(prev=>[...prev,{role:'user',content}]);await base44.agents.addMessage(conversation,{role:'user',content})}catch(e){setText(content);setError(e.message||'Could not send message.')}finally{setBusy(false)}}
  const shown=messages.filter(m=>!(m.role==='user'&&m.content?.startsWith('[Project ready event]')));
  return <section className="rounded-2xl border border-primary bg-card p-5"><h2 className="font-heading text-lg font-bold">Your project is ready</h2><div className="mt-3 space-y-3" aria-live="polite">{shown.length?shown.map((message,i)=><TemplateMessage key={message.id||i} message={message}/>):<p role="status" className="text-sm text-muted-foreground">{loading?'Opening your celebration…':'Preparing your message…'}</p>}</div><form className="mt-4 flex flex-col gap-2 sm:flex-row" onSubmit={send}><input className={input} value={text} maxLength={1000} onChange={e=>setText(e.target.value)} disabled={!conversation||loading||busy} placeholder="Reply to the guide…" aria-label="Reply to project celebrator"/><button className={primary} disabled={!conversation||loading||busy||!text.trim()}>{busy?'Sending…':'Reply'}</button></form><Failure error={error}/></section>;
}