import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Failure,input,primary,secondary} from './ui';
import HistoryMessage from './HistoryMessage';
export default function HistoryChat() {
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;async function open(){try{const result=await base44.agents.listConversations({agent_name:'prompt_history_guide'});const items=Array.isArray(result)?result:result?.conversations||[];const previous=[...items].sort((a,b)=>new Date(b.updated_date||b.created_date)-new Date(a.updated_date||a.created_date))[0];if(previous){const full=await base44.agents.getConversation(previous.id);if(active){setConversation(full);setMessages(full.messages||[])}}}catch(e){if(active)setError(e.message||'Could not load the history assistant.')}finally{if(active)setLoading(false)}}open();return()=>{active=false}},[]);
  useEffect(()=>{if(!conversation?.id)return;return base44.agents.subscribeToConversation(conversation.id,data=>setMessages(data.messages||[]))},[conversation?.id]);
  async function send(e){e.preventDefault();const content=text.trim();if(!content||busy)return;setBusy(true);setError('');try{let current=conversation;if(!current){current=await base44.agents.createConversation({agent_name:'prompt_history_guide',metadata:{name:'Prompt history search',description:'Find past prompts'}});setConversation(current)}setText('');setMessages(previous=>[...previous,{role:'user',content}]);await base44.agents.addMessage(current,{role:'user',content});}catch(e){setText(content);setError(e.message||'Could not send your question.')}finally{setBusy(false)}}
  async function newChat(){setBusy(true);setError('');try{const current=await base44.agents.createConversation({agent_name:'prompt_history_guide',metadata:{name:'Prompt history search',description:'Find past prompts'}});setConversation(current);setMessages([])}catch(e){setError(e.message||'Could not start a new search.')}finally{setBusy(false)}}
  return <div><p className="mb-3 text-sm text-muted-foreground">Ask about past prompts in plain language. For a CSV, use the filters above and Export CSV.</p><div className="max-h-[50vh] min-h-40 space-y-3 overflow-y-auto rounded-xl border border-border bg-background p-4" aria-live="polite">{loading?<p role="status">Opening assistant…</p>:messages.length?messages.map((message,i)=><HistoryMessage key={message.id||i} message={message}/>):<p className="text-sm text-muted-foreground">What would you like to find in your prompt history?</p>}</div><form className="mt-3 flex flex-col gap-2 sm:flex-row" onSubmit={send}><input className={input} value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Ask about a past prompt…" aria-label="Ask the history assistant" disabled={busy||loading}/><button className={primary} disabled={busy||loading||!text.trim()}>{busy?'Sending…':'Ask'}</button></form><button className={`${secondary} mt-3`} type="button" disabled={busy||loading} onClick={newChat}>New conversation</button><div className="mt-3"><Failure error={error}/></div></div>;
}