import {useEffect,useMemo,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Panel,Failure,Empty,primary} from './ui';
import {exportHistory} from './historyExport';
import HistoryFilters from './HistoryFilters';
import HistoryTable from './HistoryTable';
import HistoryChat from './HistoryChat';
export default function HistoryExplorer({userId}) {
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[tool,setTool]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
  useEffect(()=>{if(!userId)return;let active=true;async function load(){setLoading(true);setError('');try{const all=[];let page;do{page=await base44.entities.PromptHistory.filter({created_by_id:userId},'-submitted_at_ms',500,all.length);all.push(...page)}while(page.length===500&&active);if(active)setRows(all)}catch(e){if(active)setError(e.message||'Could not load prompt history.')}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[userId]);
  const tools=useMemo(()=>[...new Set(rows.map(row=>row.tool_used).filter(Boolean))].sort(),[rows]);
  const filtered=useMemo(()=>rows.filter(row=>{const date=new Date(row.submitted_at_ms||row.submitted_at||row.created_date);const localDay=/^\d{4}-\d{2}-\d{2}/.test(row.local_datetime||'')?row.local_datetime.slice(0,10):'';const day=localDay||(Number.isNaN(date.getTime())?'':date.toISOString().slice(0,10));return (!query||`${row.prompt||''} ${row.response||''} ${row.tool_used||''}`.toLowerCase().includes(query.toLowerCase().trim()))&&(!tool||row.tool_used===tool)&&(!from||day>=from)&&(!to||day<=to)}),[rows,query,tool,from,to]);
  return <div className="space-y-5"><Panel title="Prompt History Guide"><HistoryChat/></Panel><Panel title="Search and filter your history"><p className="mb-4 text-sm text-muted-foreground">Search past prompts and responses, narrow by tool or date, then export the matching entries.</p><HistoryFilters {...{query,setQuery,tool,setTool,tools,from,setFrom,to,setTo}}/><div className="mt-4 flex flex-wrap items-center gap-3"><button className={primary} disabled={loading||!filtered.length} onClick={()=>exportHistory(filtered)}>Export CSV ({filtered.length})</button><span className="text-sm text-muted-foreground" role="status">{loading?'Loading all your history…':`${filtered.length} of ${rows.length} entries`}</span></div><div className="mt-3"><Failure error={error}/></div></Panel><Panel title="Matching entries">{loading?<p role="status" className="text-sm text-muted-foreground">Loading entries…</p>:rows.length?<HistoryTable rows={filtered}/>:<Empty>No prompt history saved yet.</Empty>}</Panel></div>;
}