import React,{useState} from 'react';
import {base44} from '@/api/base44Client';
import {Panel,Field,Failure,Empty,input,primary} from './ui';
function extract(value,name){if(name==='conversations.json'&&Array.isArray(value)){return value.map(c=>({title:c.title||'Conversation',summary:Object.values(c.mapping||{}).flatMap(node=>{const m=node?.message;return m?.author?.role==='user'&&Array.isArray(m.content?.parts)?m.content.parts.filter(x=>typeof x==='string'):[]}).join(' ').slice(0,600)})).filter(x=>x.summary)}if(Array.isArray(value))return value.map(x=>({title:x.title||x.name||'Imported request',summary:typeof x==='string'?x: x.prompt||x.content||x.text||''})).filter(x=>typeof x.summary==='string'&&x.summary.trim());return [{title:name,summary:typeof value==='string'?value:JSON.stringify(value)}]}
export default function ImportCenter({imports,setImports,summaries,setSummaries,projects,history}) {
 const [file,setFile]=useState(null),[paste,setPaste]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function persist(name,source,items){const valid=items.map(x=>({title:String(x.title||name).slice(0,120),summary:String(x.summary||'').slice(0,600),source})).filter(x=>x.summary.trim());if(!valid.length)throw Error('No readable conversation text found. Try a JSON export, a text file or pasted notes.');if(valid.length>400)throw Error('This import has over 400 conversations. Split it into smaller files so none are silently skipped.');const record=await base44.entities.AgentImport.create({name,source,status:'Processing',count:valid.length,summaries:'Parsed locally; only short text excerpts are saved.'});try{let saved=[];for(let i=0;i<valid.length;i+=100){const batch=await base44.entities.AgentImportedSummary.bulkCreate(valid.slice(i,i+100).map(v=>({...v,import_id:record.id})));saved.push(...batch)}const done=await base44.entities.AgentImport.update(record.id,{status:'Ready',count:saved.length});setImports(x=>[done,...x]);setSummaries(x=>[...saved,...x]);setNotice(`${saved.length} scan-ready excerpts imported. Raw files stay on your device and are not stored.`)}catch(e){const failed=await base44.entities.AgentImport.update(record.id,{status:'Error',error:e.message,count:0});setImports(x=>[failed,...x]);throw e}}
 async function submit(e){e.preventDefault();if(!file&&!paste.trim())return;setBusy(true);setError('');setNotice('');try{if(file){if(file.size>15*1024*1024)throw Error('Choose a file under 15 MB. Split large exports before importing.');const text=await file.text();const content=file.name.endsWith('.json')?JSON.parse(text):text;let items;if(file.name.endsWith('.csv')){const rows=text.split(/\r?\n/).filter(Boolean);items=rows.slice(1).map((row,i)=>({title:`Row ${i+2}`,summary:row}));}else items=extract(content,file.name);await persist(file.name,file.name==='conversations.json'?'ChatGPT export':file.name.endsWith('.csv')?'CSV':file.name.endsWith('.json')?'JSON':'Text',items);setFile(null);e.target.reset()}else{await persist('Pasted conversation','Pasted text',extract(paste,'Pasted conversation'));setPaste('')}}catch(e){setError(e.message||'Could not import the file.')}finally{setBusy(false)}}
 async function sync(){setBusy(true);setError('');try{await persist('Existing Hub data','Hub sync',[...history.map(x=>({title:x.tool_used||'Hub prompt',summary:x.prompt})),...projects.map(x=>({title:x.name,summary:x.master_prompt}))]);}catch(e){setError(e.message||'Could not sync Hub data.')}finally{setBusy(false)}}
 return <div className="space-y-5"><Panel title="Import Center"><p className="mb-4 text-sm text-muted-foreground">No automatic ChatGPT access is connected. Choose a local ChatGPT conversations.json export, text, JSON or CSV; or paste a conversation. Files are parsed on this device. Only short excerpts are saved for scanning.</p><form onSubmit={submit} className="space-y-4"><Field label="Choose file"><input className={input} type="file" accept=".json,.txt,.csv,application/json,text/plain,text/csv" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="Or paste conversation text"><textarea className={input} rows="5" value={paste} onChange={e=>setPaste(e.target.value)} placeholder="Paste previous work here"/></Field><button className={primary} disabled={busy||(!file&&!paste.trim())}>{busy?'Importing…':'Parse and import'}</button></form><div className="mt-4 border-t border-border pt-4"><p className="mb-2 text-sm">Map existing Hub records: {history.length} prompt-history entries, {projects.length} Concierge projects.</p><button className={primary} disabled={busy||(!history.length&&!projects.length)} onClick={sync}>Sync internal Hub data</button></div></Panel><Failure error={error}/>{notice&&<p role="status" className="rounded-xl bg-secondary p-3 text-sm">{notice}</p>}<Panel title="Import history">{!imports.length&&<Empty>No imports yet.</Empty>}{imports.map(x=><div key={x.id} className="mb-2 rounded-xl border border-border p-3 text-sm"><b>{x.name}</b><p className="text-muted-foreground">{x.source} · {new Date(x.created_date).toLocaleDateString()} · {x.status} · {x.count||0} excerpts · {x.error||'No errors'}</p></div>)}</Panel></div>
}