import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Panel,Failure,input,primary,secondary,Empty} from './ui';
import TemplateMessage from './TemplateMessage';
export default function LearningSuggestions({data}) {
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[text,setText]=useState(''),[error,setError]=useState('');
  const projects=data.projects.slice(0,5),history=data.history.slice(0,5),sessions=data.sessions.slice(0,3),completed=data.progress.filter(item=>item.status==='completed').map(item=>item.lesson_id);
  const hasWorkflow=projects.length||history.length||sessions.length;
  const fingerprint=JSON.stringify([projects.map(p=>[p.id,p.updated_date]),history.map(h=>h.id),sessions.map(s=>s.id),completed]);
  useEffect(()=>{if(!hasWorkflow)return;let live=true;async function suggest(){setLoading(true);setError('');try{const result=await base44.agents.listConversations({agent_name:'hub_lesson_guide'});const items=Array.isArray(result)?result:result?.conversations||[];const previous=items.find(item=>item.metadata?.description===fingerprint);if(previous){const full=await base44.agents.getConversation(previous.id);if(live){setConversation(full);setMessages(full.messages||[])}}else{const current=await base44.agents.createConversation({agent_name:'hub_lesson_guide',metadata:{name:'My learning suggestions',description:fingerprint}});if(!live)return;setConversation(current);await base44.agents.addMessage(current,{role:'user',content:`[Automatic workflow review]\nSuggest relevant active HubLessonAdmin modules for my workflow.\nProjects: ${JSON.stringify(projects.map(p=>({name:p.name,category:p.category,summary:(p.summary||'').slice(0,200)})))}\nRecent prompt tasks: ${JSON.stringify(history.map(h=>({tool:h.tool_used,prompt:(h.prompt||'').slice(0,180)})))}\nAdvisor tasks: ${JSON.stringify(sessions.map(s=>(s.task||'').slice(0,180)))}\nCompleted lesson IDs: ${JSON.stringify(completed)}`})}}catch(e){if(live)setError(e.message||'Could not get learning suggestions.')}finally{if(live)setLoading(false)}}suggest();return()=>{live=false}},[fingerprint]);
  useEffect(()=>{if(!conversation?.id)return;return base44.agents.subscribeToConversation(conversation.id,update=>setMessages(update.messages||[]))},[conversation?.id]);
  async function ask(e){e.preventDefault();if(!text.trim()||!conversation||busy)return;const content=text.trim();setBusy(true);setError('');try{setText('');setMessages(previous=>[...previous,{role:'user',content}]);await base44.agents.addMessage(conversation,{role:'user',content})}catch(e){setText(content);setError(e.message||'Could not send your question.')}finally{setBusy(false)}}
  const shown=messages.filter(message=>!(message.role==='user'&&message.content?.startsWith('[Automatic workflow review]')));
  return <Panel title="Learning suggestions"><p className="mb-3 text-sm text-muted-foreground">Based on your saved projects, recent prompt tasks and lesson progress. Only active Hub modules are suggested.</p>{!hasWorkflow?<Empty>Save a project or use a prompt tool to get recommendations tailored to your workflow.</Empty>:<><div className="max-h-72 space-y-3 overflow-y-auto rounded-xl border border-border bg-background p-3" aria-live="polite">{shown.length?shown.map((message,i)=><TemplateMessage key={message.id||i} message={message}/>):<p role="status" className="text-sm text-muted-foreground">{loading?'Reviewing your workflow…':'Preparing suggestions…'}</p>}</div><form className="mt-3 flex flex-col gap-2 sm:flex-row" onSubmit={ask}><input className={input} value={text} onChange={e=>setText(e.target.value)} maxLength={1500} disabled={!conversation||loading||busy} placeholder="Ask why a module fits…" aria-label="Ask the learning guide"/><button className={primary} disabled={!conversation||loading||busy||!text.trim()}>{busy?'Sending…':'Ask'}</button></form></>}<div className="mt-3 flex flex-wrap gap-3"><a className={`${secondary} inline-flex items-center`} href="/hub.html">Open Learning Hub</a></div><Failure error={error}/></Panel>;
}