const lesson = (id, category, title, level, useCase, explanation, why, when, avoid, example, steps, related) => ({id,category,title,level,useCase,explanation,why,when,avoid,example,steps,related});
export const lessons = [
  lesson('basics','ChatGPT Basics','Start a useful conversation','Beginner','Operations','ChatGPT responds to instructions you type in a chat. Give it a goal, context, audience and the format you want.','A specific request saves editing time.','When you need a first draft or explanation.','Do not treat an answer as a verified fact.','I run Glam Hustle Hub. Explain three ways to organize weekly customer questions in a short checklist.', ['Write the goal.','Add business context.','Specify the output format.','Check facts and refine the result.'],'prompting'),
  lesson('modes','Modes and Workflows','Choose the right workflow','Beginner','Operations','Start with a chat for short tasks; use a Project to keep related context together; use specialized tools for files, images or coding.','You avoid unnecessary steps.','When planning a new task.','Do not use a complex workflow for a one-line answer.','I need a weekly content plan for Glam Hustle Hub. Recommend a simple workflow and explain why.', ['Describe your task in Advisor.','Review its recommendation.','Start small and save reusable instructions.'],'areas'),
  lesson('reasoning','Reasoning Levels','When to ask for deeper thinking','Intermediate','Building Apps','Give complex decisions more time and ask for trade-offs and checks. Fast answers suit simple rewrites. Available settings depend on your ChatGPT plan.','It helps balance speed with careful work.','For multi-step comparisons or troubleshooting.','Do not assume longer reasoning automatically makes facts correct.','Compare two ways to organize my customer onboarding. List trade-offs and test assumptions.', ['State the decision.','Ask for options and trade-offs.','Verify important claims.'],'modes'),
  lesson('areas','Chat vs Work vs Codex vs Voice vs Images','Where each task belongs','Beginner','Building Apps','Chat handles conversation; Work or workspace features can organize ongoing work where available; Codex focuses on code; Voice is hands-free; image tools create or edit visuals.','Match the surface to the job.','When selecting a starting point.','Do not assume every feature is available on every account.','I need a product image and listing. What should I do in chat versus an image tool?', ['Name the output.','Pick the suitable surface.','Check availability in your account.'],'modes'),
  lesson('projects','Projects and Organization','Keep a project together','Beginner','Operations','Group related conversations, files and instructions in a Project when your ChatGPT account supports it.','Repeated work stays consistent.','For ongoing launches or a recurring client workflow.','Do not paste private data into a shared workspace without checking access.','Help me set up a Project for Glam Hustle Hub product launches with reusable instructions.', ['Name the project.','Add its goal and rules.','Keep related chats together.'],'basics'),
  lesson('files','Files and Uploads','Ask better questions about files','Beginner','Operations','Upload a supported file in ChatGPT, then say what to extract, compare or summarize. Review numbers against the original.','You can turn raw documents into decisions.','For invoices, notes or CSV analysis.','Do not upload sensitive material without confirming privacy and permission.','Summarize this CSV by month. Flag missing values and explain any calculation assumptions.', ['Check file permissions.','Upload the file in ChatGPT.','Ask a bounded question.','Spot-check the answer.'],'research'),
  lesson('connected','Connected Apps/Plugins','Use connected tools safely','Intermediate','Operations','Connected tools can read or act in other services only after explicit setup and permissions. Availability varies.','You can reduce copying between apps.','When a task needs real data from another service.','Do not claim a service is connected just because it appears in a lesson.','List the information you would need from my calendar before planning content. Do not access it yet.', ['Check whether a connector exists.','Review its permissions.','Authorize it before requesting real data.'],'files'),
  lesson('prompting','Prompting Basics','Write a clear prompt','Beginner','Marketing','A useful prompt states role, goal, audience, constraints, input and output format.','Clear prompts produce easier-to-use drafts.','Whenever the first answer is too generic.','Do not bury the main task under conflicting rules.','Act as a marketing assistant. Draft three friendly captions for beginner AI learners, under 100 words each.', ['Write the outcome.','Add audience and constraints.','Give an example if useful.','Review and iterate.'],'business'),
  lesson('business','Prompting for Business','Turn an idea into an offer','Intermediate','Marketing','Ground the prompt in your actual product, buyer, price and voice. Ask for assumptions to be marked.','The result becomes relevant to your customers.','For product pages, campaigns and support copy.','Do not publish invented testimonials or claims.','Using only these product details [paste details], write a product listing with benefits and FAQs. Mark unknowns.', ['Supply verified details.','Choose audience and channel.','Check every claim.'],'content'),
  lesson('build','Building with AI','Write a safer build brief','Intermediate','Building Apps','Describe users, screens, data, permissions and acceptance checks before asking AI to build.','Clear scope prevents broken or unnecessary features.','For app features or prompt generators.','Do not deploy generated changes without reviewing flows.','Draft a build brief for an app that tracks prompts. Include users, fields, actions and security checks.', ['List existing functionality.','Define the new flow.','Specify what must stay unchanged.','Review with real data.'],'audit'),
  lesson('research','Research Workflows','Verify what is current','Intermediate','Marketing','For current facts, use a research-capable tool, request sources and check dates.','Recent information can become stale quickly.','For market and product comparisons.','Do not cite a source you have not opened.','Research three current ways small businesses use AI. Cite dated sources and separate facts from opinions.', ['Define the question.','Request cited sources.','Check dates and original pages.'],'updates'),
  lesson('audit','App Audit Workflows','Review an app step by step','Advanced','Building Apps','Audit navigation, forms, permissions, persistence, errors and mobile usability with repeatable checks.','You catch issues before launch.','Before publishing or after changes.','Do not call a flow tested if it was not actually run.','Create an app audit checklist for sign-up, saving a prompt, reopening it and using it on mobile.', ['Pick a user journey.','List expected results.','Run the journey.','Record defects and retest.'],'build'),
  lesson('content','Content Workflows','Plan a reusable content batch','Intermediate','Marketing','Batch related posts from a verified offer and adapt each to the channel.','Reusable briefs save time without repetitive copy.','For campaigns and education series.','Do not publish unreviewed claims or identical posts everywhere.','Using this offer [details], draft a one-week content plan for beginners. Include a review checklist.', ['Collect the offer details.','Set channels and goals.','Draft and review.'],'business'),
  lesson('images','Image Workflows','Brief an image tool clearly','Intermediate','Marketing','Describe subject, composition, palette and constraints; iterate based on the actual output.','Specific visual direction improves consistency.','For concept images and product mockups.','Do not represent AI-generated imagery as a real product photo.','Create a clean product concept image: [product], royal blue and gold accents, no text, studio lighting.', ['State subject and purpose.','Add layout and style.','Review output and revise.'],'areas'),
  lesson('automation','Automation/Efficiency','Find a repeatable process','Advanced','Operations','Track tasks you repeat, isolate fixed rules and variable inputs, then create a reviewed template.','A stable process saves time and reduces mistakes.','For weekly reports or repeat customer responses.','Do not automate a process that still needs judgment without checkpoints.','Identify which steps in this weekly workflow can be templated and which need human review: [steps].', ['Collect examples.','Group repeated steps.','Keep human approval.'],'audit'),
  lesson('updates',"What's New in ChatGPT",'Check changes without guessing','Beginner','Operations','Read dated official announcements, then record how a change affects your actual work. The Intelligence feed here is manually managed, not live.','You avoid acting on rumors.','When a tool or feature seems different.','Do not treat example entries as current announcements.','Summarize this official announcement [paste link/text] and say whether it affects my products.', ['Open the original source.','Check the date.','Record a useful action.'],'research')
];
export const starterPrompts = [
 ['Build a Base44 App','Building','Act as a product builder. Build [app goal] for [audience]. Preserve existing functionality. Define screens, data, permissions, working actions, empty states and mobile behavior. Do not claim testing without running it.'],
 ['Build a Prompt Generator','Building','Design a prompt generator for [use case]. Specify inputs, validation, generation rules, output format, copy/save behavior and examples. Preserve user-entered details exactly.'],
 ['App Audit/Testing Review','Building','Review [app and user journey]. Check navigation, forms, permissions, persistence, errors and mobile usability. Report steps, expected outcome, observed outcome and severity. Do not invent test results.'],
 ['Master Build Prompt Creator','Building','Turn [feature idea] into a clear build prompt. Separate fixed requirements from variables, list user flows and acceptance criteria, and identify anything needing clarification.'],
 ['Marketing Campaign Prompt','Marketing','Create a campaign for [verified offer] aimed at [audience] on [channels]. Use [brand voice], include goals, posts, calls to action and a fact-check checklist. Never invent claims.'],
 ['Image Prompt Creator','Images','Write an image prompt for [subject] used for [purpose]. Describe composition, color, lighting and exclusions; avoid adding text unless requested.'],
 ['Product Listing Prompt','Commerce','Using only these facts [product details], write a clear listing for [buyer]. Include benefits, specifications and FAQs. Mark missing details rather than inventing them.'],
 ['Troubleshooting Prompt','Operations','Help diagnose [issue]. Ask for observable symptoms, reproduction steps and recent changes. Rank likely causes, propose reversible checks and explain how to confirm a fix.'],
 ['Lesson/Tutorial Builder','Teaching','Teach [topic] to [audience]. Explain simply, say why and when it matters, show an exact example and give step-by-step practice plus a short check for understanding.'],
 ['Workflow Handoff Prompt','Operations','Document [workflow] for [person/team]. Include trigger, inputs, ordered steps, owners, decisions, expected output, exceptions and a confirmation checklist.']
].map(([name,category,body])=>({name,category,body,purpose:'Editable starter template',status:'starter',version:1,times_used:0,source:'starter'}));