import React,{useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Panel,Failure,input,primary,secondary} from './ui';
import SetupMessage from './SetupMessage';
export default function SetupGuide({projects,setProjects}) {
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;async function open(){try{const list=await base44.agents.listConversations({agent_name:'hub_project_setup'});const previous=Array.isArray(list)?list[0]:list?.conversations?.[0];if(previous){const full=await base44.agents.getConversation(previous.id);if(active){setConversation(full);setMessages(full.messages||[]);}}}catch(e){if(active)setError(e.message||'Could not open your setup conversation.')}finally{if(active)setLoading(false)}}open();return()=>{active=false}},[]);
  useEffect(()=>{if(!conversation?.id)return;return base44.agents.subscribeToConversation(conversation.id,data=>setMessages(data.messages||[]))},[conversation?.id]);
  useEffect(()=>base44.entities.HubProject.subscribe(event=>{if(event.type==='create'&&event.data)setProjects(previous=>[event.data,...previous.filter(project=>project.id!==event.data.id)])}),[setProjects]);
  async function send(e){e.preventDefault();const content=text.trim();if(!content||busy)return;setBusy(true);setError('');try{let current=conversation;if(!current){current=await base44.agents.createConversation({agent_name:'hub_project_setup',metadata:{name:'New HubProject setup',description:'Guided first project setup'}});setConversation(current)}setText('');setMessages(previous=>[...previous,{role:'user',content}]);await base44.agents.addMessage(current,{role:'user',content});}catch(e){setText(content);setError(e.message||'Could not send your message. Please try again.')}finally{setBusy(false)}}
  async function startOver(){setBusy(true);setError('');try{const next=await base44.agents.createConversation({agent_name:'hub_project_setup',metadata:{name:'New HubProject setup',description:'Guided first project setup'}});setConversation(next);setMessages([]);}catch(e){setError(e.message||'Could not start a new setup.')}finally{setBusy(false)}}
  async function refresh(){setBusy(true);setError('');try{setProjects(await base44.entities.HubProject.list('-created_date',500))}catch(e){setError(e.message||'Could not load projects.')}finally{setBusy(false)}}
  return <div className="space-y-5"><Panel title="New project setup guide"><p className="text-sm text-muted-foreground">Tell the guide what you want to work on. It will ask a few questions, review your answers, and save a starting project only when you say yes.</p><button type="button" className={`${secondary} mt-3`} onClick={startOver} disabled={busy||loading}>Start a new setup</button></Panel><Panel title="Conversation"><div aria-live="polite" className="max-h-[55vh] min-h-48 space-y-3 overflow-y-auto rounded-xl border border-border bg-background p-4">{loading?<p role="status" className="text-sm text-muted-foreground">Opening your setup…</p>:messages.length?messages.map((message,i)=><SetupMessage key={message.id||i} message={message}/>):<p className="text-sm text-muted-foreground">Hi! What would you like to call your new project?</p>}</div><form onSubmit={send} className="mt-4 flex flex-col gap-2 sm:flex-row"><input className={input} value={text} onChange={e=>setText(e.target.value)} placeholder="Type your answer…" aria-label="Message the setup guide" maxLength={4000} disabled={busy||loading}/><button className={primary} disabled={busy||loading||!text.trim()}>{busy?'Sending…':'Send'}</button></form><div className="mt-3"><Failure error={error}/></div></Panel><Panel title="Your saved projects"><button className={secondary} onClick={refresh} disabled={busy}>Refresh projects</button>{projects.length?<ul className="mt-3 space-y-2 text-sm">{projects.slice(0,10).map(project=><li key={project.id} className="rounded-xl border border-border p-3"><b>{project.name}</b><span className="ml-2 text-muted-foreground">{project.status||'Building'}</span>{project.summary&&<p className="mt-1 text-muted-foreground">{project.summary}</p>}</li>)}</ul>:<p className="mt-3 text-sm text-muted-foreground">No saved projects yet. Finish the conversation to create your first one.</p>}</Panel></div>;
}