import {useEffect,useMemo,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Failure,Field,input,primary,secondary} from './ui';
export default function TemplateConfigurator({template,project,onSaved}) {
  const [values,setValues]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const variables=useMemo(()=>[...new Set([...template.prompt.matchAll(/\[([^\[\]\n]{1,80})\]/g)].map(match=>match[1]))],[template.id,template.prompt]);
  useEffect(()=>{setValues({});setError('');setNotice('')},[template.id,project.id]);
  const complete=variables.every(variable=>values[variable]?.trim());
  const preview=template.prompt.replace(/\[([^\[\]\n]{1,80})\]/g,(_,variable)=>values[variable]?.trim()||`[${variable}]`);
  async function apply(){if(!complete||busy)return;if(!window.confirm(project.master_prompt?'Replace this project’s existing master prompt with the reviewed template preview?':'Save this reviewed template as this project’s master prompt?'))return;setBusy(true);setError('');setNotice('');try{const updated=await base44.entities.HubProject.update(project.id,{master_prompt:preview});onSaved(updated);setNotice('Saved to this project. You can continue refining it in Prompt Concierge.')}catch(e){setError(e.message||'Could not save the prompt to this project.')}finally{setBusy(false)}}
  return <div className="space-y-4"><p className="text-sm text-muted-foreground">{template.description||'Customize this template for your project.'}</p>{variables.length?<div className="grid gap-3 sm:grid-cols-2">{variables.map(variable=><Field key={variable} label={variable}><input className={input} value={values[variable]||''} onChange={e=>setValues(current=>({...current,[variable]:e.target.value}))} placeholder={`Enter ${variable}`} maxLength={1000}/></Field>)}</div>:<p className="text-sm text-muted-foreground">This template has no bracketed fields to fill in.</p>}<div><b className="text-sm">Preview for {project.name}</b><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl border border-border bg-background p-4 text-sm">{preview}</pre></div>{project.master_prompt&&<p className="text-sm text-muted-foreground">This project already has a master prompt. Applying this template will replace it after your confirmation.</p>}<div className="flex flex-wrap gap-2"><button type="button" className={primary} disabled={busy||!complete} onClick={apply}>{busy?'Saving…':'Apply to project'}</button><button type="button" className={secondary} onClick={()=>navigator.clipboard.writeText(preview)} disabled={!complete||busy}>Copy preview</button></div><Failure error={error}/>{notice&&<p role="status" className="text-sm text-primary">{notice}</p>}</div>;
}