import {useEffect,useState} from 'react';
import {base44} from '@/api/base44Client';
import {Failure,input,primary} from './ui';
import TemplateMessage from './TemplateMessage';
export default function TemplateChat({project}) {
  const [conversation,setConversation]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;async function open(){setLoading(true);try{const result=await base44.agents.listConversations({agent_name:'hub_template_guide'});const items=Array.isArray(result)?result:result?.conversations||[];const previous=items.filter(item=>item.metadata?.description===project.id).sort((a,b)=>new Date(b.updated_date||b.created_date)-new Date(a.updated_date||a.created_date))[0];if(previous){const full=await base44.agents.getConversation(previous.id);if(active){setConversation(full);setMessages(full.messages||[])}}else if(active){setConversation(null);setMessages([])}}catch(e){if(active)setError(e.message||'Could not open the template guide.')}finally{if(active)setLoading(false)}}open();return()=>{active=false}},[project.id]);
  useEffect(()=>{if(!conversation?.id)return;return base44.agents.subscribeToConversation(conversation.id,data=>setMessages(data.messages||[]))},[conversation?.id]);
  async function send(e){e.preventDefault();const content=text.trim();if(!content||busy||loading)return;setBusy(true);setError('');try{let current=conversation;if(!current){current=await base44.agents.createConversation({agent_name:'hub_template_guide',metadata:{name:`Templates for ${project.name}`,description:project.id}});setConversation(current)}setText('');setMessages(previous=>[...previous,{role:'user',content}]);await base44.agents.addMessage(current,{role:'user',content:`Selected project ID: ${project.id}\nProject name: ${project.name}\nCategory: ${project.category||'Unspecified'}\nGoal: ${project.summary||'Unspecified'}\nQuestion: ${content}`});}catch(e){setText(content);setError(e.message||'Could not send your question.')}finally{setBusy(false)}}
  return <div><p className="mb-3 text-sm text-muted-foreground">Ask which active template fits this project, or how to fill its placeholders.</p><div className="max-h-[45vh] min-h-36 space-y-3 overflow-y-auto rounded-xl border border-border bg-background p-4" aria-live="polite">{loading?<p role="status">Opening guide…</p>:messages.length?messages.map((message,i)=><TemplateMessage key={message.id||i} message={message}/>):<p className="text-sm text-muted-foreground">Tell me what you want this project to produce, and I’ll help you choose a template.</p>}</div><form className="mt-3 flex flex-col gap-2 sm:flex-row" onSubmit={send}><input className={input} value={text} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Ask about templates…" aria-label="Message the template guide" disabled={busy||loading}/><button className={primary} disabled={busy||loading||!text.trim()}>{busy?'Sending…':'Ask'}</button></form><div className="mt-3"><Failure error={error}/></div></div>;
}