import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import ProjectReadyAgent from '@/components/projects/ProjectReadyAgent';
export default function HubProjectDetail() {
  const {id}=useParams(),[project,setProject]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{let live=true;async function load(){setLoading(true);try{const record=await base44.entities.HubProject.get(id);if(live)setProject(record||null)}catch(e){if(live)setError(e.message||'Could not load this project.')}finally{if(live)setLoading(false)}}load();const unsubscribe=base44.entities.HubProject.subscribe(event=>{if(event.id===id&&live){if(event.type==='delete')setProject(null);else if(event.data)setProject(event.data)}});return()=>{live=false;unsubscribe()}},[id]);
  const readyToday=project?.status==='Ready to Use'&&project?.ready_at&&new Date(project.ready_at).toDateString()===new Date().toDateString();
  async function copy(){try{await navigator.clipboard.writeText(project.master_prompt||'');setNotice('Master prompt copied.')}catch(e){setNotice('Could not copy your master prompt.')}}
  return <main className="min-h-screen bg-background px-4 py-8 text-foreground"><div className="mx-auto max-w-3xl space-y-5"><Link className="text-sm text-primary underline" to="/agent-center?section=setup">Back to projects</Link>{loading?<p role="status">Loading project…</p>:error?<p role="alert" className="text-destructive">{error}</p>:!project?<p>Project not found.</p>:<><header className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{project.category||'Project'} · {project.status||'Building'}</p><h1 className="mt-1 font-heading text-2xl font-bold">{project.name}</h1>{project.summary&&<p className="mt-2 text-sm text-muted-foreground">{project.summary}</p>}</header>{readyToday&&<ProjectReadyAgent key={`${project.id}:${project.ready_at}`} project={project}/>}<section className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-heading text-lg font-bold">Master prompt</h2>{project.master_prompt&&<button type="button" onClick={copy} className="min-h-11 rounded-xl border border-border bg-secondary px-4 py-2 text-sm font-semibold">Copy prompt</button>}</div><pre className="mt-3 whitespace-pre-wrap break-words text-sm leading-6">{project.master_prompt||'No master prompt saved yet.'}</pre>{notice&&<p role="status" className="mt-3 text-sm text-muted-foreground">{notice}</p>}</section></>}</div></main>;
}